import React from "react";
import { ScrollView, Text, View } from "react-native";

const TermsAndConditions = () => {
  return (
    <ScrollView className="flex-1">
      <View className="p-4">
        <Text className="text-2xl text-primary font-bold text-center mb-4">
          Terms of Use for Information Dissmination
        </Text>
        <Text className="text-secondary  mb-2">
          This document is an electronic record in terms of the Information
          Technology Act, 2000 and the rules thereunder. It is generated by a
          computer system and does not require any physical or digital
          signatures. This document is published in accordance with Rule 3(1) of
          the Information Technology (Intermediaries Guidelines) Rules, 2011,
          which mandates the publishing of the rules and regulations, privacy
          policy, and terms of use for access or usage of Just Search's portal
          through the Just Search platform. This document also satisfies the
          requirements under Section 65B(2) of the Indian Evidence Act, 1872.
          Your Acceptance of This Agreement: This is an agreement between you
          (“You” or “Your”) and Just Search Limited, a company registered under
          the Companies Act, 1956 with its registered office at Granthlok 5-A
          near police station ,new pali road bhagat ki kothi jodhpur 342001
          ("Just Search", "we", or "our"). This agreement governs your use of
          the search services provided by Just Search through its website
          www.justsearch.net.in ("Website"), telephone search, SMS, or any other
          medium (collectively called "Platforms"). By accessing or using any
          Platform, you agree to be bound by these Terms and Conditions.
          Modifications: We may modify these Terms and the Website from time to
          time without notice. It is your responsibility to review the Terms
          periodically. Modified Terms are effective immediately upon posting,
          and your continued use of the Website after changes are made indicates
          your acceptance of the updated Terms. How You May Use Our Content: We
          provide various information, text, photographs, designs, graphics,
          images, sound and video recordings, animations, content,
          advertisements, and other materials (collectively, the "Content") on
          the Platforms for search services. This Content is provided solely for
          your personal and non-commercial use. Every effort is made to verify
          the authenticity of the Platform content. However, Just Search is not
          responsible for any direct or indirect damage, loss, or action arising
          from access to or use of the Platform content—including data loss,
          revenue loss, profit loss, property damage, virus infection, etc. You
          may view, use, copy, and distribute Content from the Platforms for
          internal, non-commercial, and informational purposes only. The use of
          automated processes like data mining, scraping, crawling, or automated
          queries is prohibited. You may not use the Platforms to develop a
          competing listing service or send unsolicited commercial emails.
          Except for the limited rights expressly stated, you are not granted
          any license to copyrights, trademarks, patents, or other intellectual
          property rights. How You May Use Our Trademarks: The name "Just
          Search", its logos, service and product names, design marks, and
          slogans are the trademarks of Just Search or its wholly owned
          subsidiaries. All other marks are the property of their respective
          owners. Any content copied from the Platforms must retain all
          copyright, trademark, and other proprietary notices. Use of the Just
          Search name or marks for advertising, promotion, or any commercial use
          is prohibited without written permission. For permission, email:
          justsearch.help@gmail.com How We May Use Information You Provide to
          Us: Do not send us any confidential or proprietary information. Except
          as outlined in our Privacy Policy, any information you submit to us
          (including feedback, responses, questions, suggestions, etc.) will be
          considered non-confidential and non-proprietary. We are free to
          reproduce, use, and distribute such information to others. User
          Reviews, Ratings, and Comments: Just Search offers information
          directory services through various mediums (SMS, email, website, app,
          and calls). Any reviews, ratings, and comments submitted by you via
          these mediums (“Communications”) are subject to additional rules. You
          are solely responsible for the content you post on the Website or any
          Platform. Just Search does not endorse any of your content. When you
          post public content, you grant Just Search a non-exclusive, worldwide,
          perpetual, royalty-free license to use it. Just Search reserves the
          right to remove any content that is objectionable or violates these
          Terms. You are fully liable for any legal issues arising from your
          posts and agree to indemnify Just Search for any resulting claims.
          Privacy Policy: Just Search is committed to protecting the privacy and
          security of the personal information of its customers, business
          partners, and users. For more details, please refer to our Privacy
          Policy. Content Disclaimer: Just Search disseminates information
          provided by advertisers, developers, publishers, agents, users, etc.
          Every effort has been made to ensure the authenticity of Platform
          content, but Just Search does not guarantee its accuracy, quality,
          legality, or take responsibility for any damage or losses. Product and
          service prices and availability are subject to change without notice.
          Users should exercise discretion when using the Platforms. We are not
          responsible for the content, security, or performance of external
          websites. Third Party Sites: If you engage in transactions with
          advertisers or service providers on the Platforms, it is solely
          between you and the other party. Just Search is not responsible for
          any such dealings. Indemnification: You agree to indemnify and hold
          harmless Just Search (and its affiliates, directors, employees, etc.)
          from any claim, demand, or legal fees arising from your violation of
          these Terms, law, or rights of another. These obligations will survive
          termination of the Terms.
        </Text>
      </View>
    </ScrollView>
  );
};

export default TermsAndConditions;
