name: Build CICD

on:
  push:
    branches: [ main ]

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      web: ${{ steps.filter.outputs.web }}
      api: ${{ steps.filter.outputs.api }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            web:
              - 'apps/web/**'
              - 'packages/**'
            backend:
              - 'apps/backend/**'
              - 'packages/**'
            dashboard:
              - 'apps/dashboard/**'
              - 'packages/**'
  build-web:
    needs: detect
    if: needs.detect.outputs.web == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Web Image
        run: |
          docker build \
            -f apps/web/Dockerfile \
            -t myorg/web:latest \
            .

      - name: Push Web Image
        run: |
          docker push myorg/web:latest
  build-backend:
    needs: detect
    if: needs.detect.outputs.api == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Backend Image
        run: |
          docker build \
            -f apps/backend/Dockerfile \
            -t myorg/backend:latest \
            .
