version: "3.9"

services:
  valkey:
    image: valkey/valkey:8.1.3
    container_name: valkey
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
      - ./valkey.conf:/etc/valkey/valkey.conf
    command: ["valkey-server", "/etc/valkey/valkey.conf"]
